"""
Backtest / Validation script — the heart of the thesis evaluation chapter.

Replays the historical period in two parallel scenarios:
  • As-Is:  follow the actual decisions captured in the data
  • To-Be:  what the agent WOULD have decided each day

Computes KPIs for both and writes a comparison report.

Three cost scenarios available:
  • conservative (~12% holding rate)
  • realistic    (~20% holding rate, default)
  • aggressive   (~28% holding rate)

Plus optional sensitivity analysis varying lead time, demand, and holding rate.

Usage:
    python scripts/run_validation.py
    python scripts/run_validation.py --window-days 90 --scenario realistic
    python scripts/run_validation.py --sensitivity
    python scripts/run_validation.py --all-scenarios
"""
from __future__ import annotations

import argparse
import sys
from copy import deepcopy
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path

# Ensure project root is on sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd

from src.agent.replenishment import ReplenishmentAgent
from src.config import config
from src.data_layer.models import (
    CONSUMPTION_MOVEMENT_TYPES, GOODS_RECEIPT_MOVEMENT_TYPE,
)
from src.data_layer.repository import Repository
from src.mrp.engine import MRPEngine
from src.rules.engine import RulesEngine
from src.utils.as_of_date import get_effective_today
from src.utils.cost_estimator import (
    SCENARIOS, get_scenario, CostScenario,
    HoldingCostComponents, StockoutCostParams,
)
from src.utils.kpi import (
    KPICalculator, KPIReport, compare_scenarios, sensitivity_pivot,
)
from src.utils.logger import log


# Review cadence of the agent inside the To-Be simulation (days)
REVIEW_INTERVAL_DAYS = 7
# Initial stock when no snapshot exists before the window: × safety stock
DEFAULT_INITIAL_STOCK_FACTOR = 2.0
STRESS_INITIAL_STOCK_FACTOR = 0.5


# ============================================================
# Backtest simulator
# ============================================================
@dataclass
class SimulationState:
    """Mutable state tracked through the simulation."""
    stock_history: list = None
    demand_history: list = None
    orders_placed: list = None
    n_proposals: int = 0          # To-Be only: intentions generated by the agent

    def __post_init__(self):
        self.stock_history = self.stock_history or []
        self.demand_history = self.demand_history or []
        self.orders_placed = self.orders_placed or []


def _to_df(rows: list, columns: list) -> pd.DataFrame:
    if not rows:
        return pd.DataFrame(columns=columns)
    return pd.DataFrame(rows)


def _initial_stock(repo: Repository, material, start: date,
                   initial_stock_factor: float | None) -> float:
    """Opening stock of the simulation window — identical for As-Is and To-Be.

    Resolution order:
      1. `initial_stock_factor` given (stress test) → factor × safety stock,
         the same for every material — an explicit "what-if" starting point.
      2. A stock snapshot on/before the day before the window → that value.
      3. Only later snapshots exist (the usual single-extraction dataset) →
         roll the nearest later snapshot back through the movement history
         (Repository.get_stock_at). This reproduces the true historical
         stock level whenever the movement export is complete.
      4. No usable snapshot (or an inconsistent roll-back < 0) →
         DEFAULT_INITIAL_STOCK_FACTOR × safety stock, so that As-Is and
         To-Be still start from the same point.
    """
    ss = float(material.safety_stock or 0)
    if initial_stock_factor is not None:
        return ss * initial_stock_factor

    qty, source = repo.get_stock_at(material.material_id, start - timedelta(days=1))
    if qty is not None and qty >= 0:
        return float(qty)
    return ss * DEFAULT_INITIAL_STOCK_FACTOR


def simulate_asis(
    repo: Repository,
    start: date,
    end: date,
    lead_time_multiplier: float = 1.0,
    demand_multiplier: float = 1.0,
    initial_stock_factor: float | None = None,
) -> SimulationState:
    """As-Is: replay actual consumption + the actual goods receipts (101).

    Stock dynamics are the SAME as in To-Be (lost-sales model): demand that
    cannot be served from stock is lost and stock never goes negative.
    Receipts are the historical purchase receipts as they happened.
    """
    state = SimulationState()
    materials = repo.get_all_materials()

    for m in materials:
        mid = m.material_id
        stock = _initial_stock(repo, m, start, initial_stock_factor)

        movements = repo.get_all_movements(mid, start=start, end=end)
        movements = sorted(movements, key=lambda x: x.posting_date)

        current = start
        movement_idx = 0
        while current <= end:
            while (movement_idx < len(movements)
                   and movements[movement_idx].posting_date <= current):
                mv = movements[movement_idx]

                if mv.movement_type in CONSUMPTION_MOVEMENT_TYPES:
                    requested = abs(mv.quantity) * demand_multiplier
                    delivered = min(requested, max(stock, 0.0))
                    stock = max(stock - requested, 0.0)
                    state.demand_history.append({
                        "date":          current,
                        "material_id":   mid,
                        "requested_qty": requested,
                        "delivered_qty": delivered,
                    })
                elif mv.movement_type == GOODS_RECEIPT_MOVEMENT_TYPE:
                    qty = abs(mv.quantity)
                    stock += qty
                    state.orders_placed.append({
                        "date":        current,
                        "material_id": mid,
                        "quantity":    qty,
                        "unit_cost":   m.standard_cost or 0,
                    })
                else:
                    # Transfers, reversals, adjustments: apply the signed
                    # quantity so the stock trajectory stays faithful.
                    stock = max(stock + mv.quantity, 0.0)

                movement_idx += 1

            state.stock_history.append({
                "date":        current,
                "material_id": mid,
                "quantity":    max(stock, 0.0),
            })
            current += timedelta(days=1)

    return state


def simulate_tobe(
    repo: Repository,
    start: date,
    end: date,
    horizon: int = 60,
    lead_time_multiplier: float = 1.0,
    demand_multiplier: float = 1.0,
    rules_engine: RulesEngine | None = None,
    initial_stock_factor: float | None = None,
    review_interval: int = REVIEW_INTERVAL_DAYS,
    forecast_method: str = "moving_average",
) -> SimulationState:
    """To-Be: the agent reviews every `review_interval` days and may issue
    orders, which arrive after the material's lead time.

    Look-ahead protection: at every review date the agent perceives only
    movements posted on or before that date (Repository filters by as_of);
    the actual demand of the following days is used solely to drive the
    simulation and the KPIs.

    Args:
        rules_engine: custom RulesEngine (e.g. with disabled rules for the
            ablation study). Default: all rules active.
        initial_stock_factor: if given, every material starts from
            factor × safety stock (stress test: 0.5). Default None →
            historical stock reconstructed from snapshots + movements
            (see _initial_stock).
    """
    state = SimulationState()
    materials = repo.get_all_materials()
    materials_by_id = {m.material_id: m for m in materials}

    stock_levels: dict[str, float] = {}
    pending_orders: dict[str, list[tuple[date, float]]] = {}
    for m in materials:
        mid = m.material_id
        stock_levels[mid] = _initial_stock(repo, m, start, initial_stock_factor)
        pending_orders[mid] = []

    # Pre-fetch actual demand, and inherit the supply PIPELINE that existed
    # at the window start: a goods receipt posted within the first lead-time
    # days of the window stems from an order placed BEFORE the window, i.e.
    # a decision the agent could not have influenced. As-Is replays those
    # receipts, so To-Be must start with the same in-transit orders —
    # otherwise the agent would be penalised for the planner's pipeline.
    demand_lookup: dict[tuple[str, date], float] = {}
    for m in materials:
        mid = m.material_id
        pipeline_end = start + timedelta(days=int(m.lead_time_days or 0))
        movements = repo.get_all_movements(mid, start=start, end=end)
        for mv in movements:
            if mv.movement_type in CONSUMPTION_MOVEMENT_TYPES:
                key = (mid, mv.posting_date)
                demand_lookup[key] = (
                    demand_lookup.get(key, 0.0) + abs(mv.quantity) * demand_multiplier
                )
            elif (mv.movement_type == GOODS_RECEIPT_MOVEMENT_TYPE
                  and mv.posting_date <= pipeline_end):
                pending_orders[mid].append((mv.posting_date, abs(mv.quantity)))

    mrp = MRPEngine(
        horizon_days=horizon,
        ordering_cost=config.default_ordering_cost,
        holding_rate=config.default_holding_rate,
    )
    rules = rules_engine if rules_engine is not None else RulesEngine()
    agent = ReplenishmentAgent(repo, mrp, rules, forecast_method=forecast_method)

    current = start
    days_since_review = 0

    while current <= end:
        # 1. Process pending arrivals
        for mid, queue in pending_orders.items():
            still_pending = []
            for (arrival, qty) in queue:
                if arrival <= current:
                    stock_levels[mid] += qty
                    state.orders_placed.append({
                        "date":        arrival,
                        "material_id": mid,
                        "quantity":    qty,
                        "unit_cost":   materials_by_id[mid].standard_cost or 0,
                    })
                else:
                    still_pending.append((arrival, qty))
            pending_orders[mid] = still_pending

        # 2. Apply demand
        for m in materials:
            mid = m.material_id
            d = demand_lookup.get((mid, current), 0.0)
            if d > 0:
                requested = d
                delivered = min(requested, stock_levels[mid])
                stock_levels[mid] = max(stock_levels[mid] - requested, 0)
                state.demand_history.append({
                    "date":          current,
                    "material_id":   mid,
                    "requested_qty": requested,
                    "delivered_qty": delivered,
                })

        # 3. Snapshot
        for mid, qty in stock_levels.items():
            state.stock_history.append({
                "date":        current,
                "material_id": mid,
                "quantity":    qty,
            })

        # 4. Periodic review
        if days_since_review >= review_interval or current == start:
            days_since_review = 0
            agent.perceive(as_of=current)
            agent.beliefs.current_stock = dict(stock_levels)
            agent.beliefs.open_orders = {
                mid: [_FakePO(arrival, qty)
                      for arrival, qty in pending_orders.get(mid, [])]
                for mid in stock_levels
            }
            agent.deliberate(as_of=current)
            state.n_proposals += len(agent.intentions)

            # Firm only the proposals whose release date falls before the
            # next review (the "opening period" of an MRP run): later
            # planned orders are re-planned at the next review with fresher
            # data. Placing every 60-day-horizon proposal at once would lock
            # in stale, buffered orders and overstate the agent's inventory.
            firm_until = current + timedelta(days=review_interval - 1)
            for intention in agent.intentions:
                if intention.proposed_date > firm_until:
                    continue
                effective_lt = (
                    int(materials_by_id[intention.material_id].lead_time_days or 0)
                    * lead_time_multiplier
                )
                arrival = intention.proposed_date + timedelta(days=int(effective_lt))
                pending_orders[intention.material_id].append(
                    (arrival, float(intention.proposed_qty))
                )
        else:
            days_since_review += 1

        current += timedelta(days=1)

    return state


class _FakePO:
    def __init__(self, expected_date: date, quantity: float):
        self.expected_date = expected_date
        self.quantity = quantity


def kpis_from_state(
    state: SimulationState,
    materials_df: pd.DataFrame,
    scenario: CostScenario,
    start: date,
    end: date,
) -> KPIReport:
    """Turn a simulation state into a KPI report on the WINDOW cost basis."""
    period_days = (end - start).days + 1
    return KPICalculator(
        stock_history=_to_df(state.stock_history, ["date", "material_id", "quantity"]),
        demand_history=_to_df(state.demand_history,
                              ["date", "material_id", "requested_qty", "delivered_qty"]),
        orders=_to_df(state.orders_placed,
                      ["date", "material_id", "quantity", "unit_cost"]),
        materials=materials_df,
        holding_rate=scenario.holding,
        stockout_params=scenario.stockout,
        ordering_cost_per_order=config.default_ordering_cost,
        period_days=period_days,
    ).report()


# ============================================================
# Single-scenario backtest
# ============================================================
def run_scenario(
    repo: Repository,
    materials_df: pd.DataFrame,
    start: date,
    end: date,
    scenario: CostScenario,
    lead_time_multiplier: float = 1.0,
    demand_multiplier: float = 1.0,
    forecast_method: str = "moving_average",
) -> tuple[KPIReport, KPIReport]:
    """Run As-Is and To-Be for a given cost scenario, return both reports."""
    log.info(f"Running As-Is for scenario '{scenario.name}'...")
    asis = simulate_asis(repo, start, end, lead_time_multiplier, demand_multiplier)

    log.info(f"Running To-Be for scenario '{scenario.name}'...")
    tobe = simulate_tobe(repo, start, end, 60, lead_time_multiplier, demand_multiplier,
                         forecast_method=forecast_method)

    asis_kpi = kpis_from_state(asis, materials_df, scenario, start, end)
    tobe_kpi = kpis_from_state(tobe, materials_df, scenario, start, end)
    return asis_kpi, tobe_kpi


# ============================================================
# Reporting
# ============================================================
def print_comparison_report(
    asis: KPIReport, tobe: KPIReport, scenario_name: str = ""
) -> pd.DataFrame:
    """Print and return the comparison DataFrame."""
    df = compare_scenarios(asis, tobe)

    print(f"\n{'═' * 70}")
    print(f"  Scenario: {scenario_name.upper()}")
    print(f"  Cost basis: {asis.period_days}-day window "
          f"(holding = avg inventory value × annual rate × {asis.period_days}/365; "
          f"annualised equivalents in *_annualized rows)")
    print(f"{'═' * 70}")

    # Group by category for prettier output
    sl_metrics = ["cycle_service_level_pct", "fill_rate_pct", "stockout_days"]
    cost_metrics = ["holding_cost_eur", "capital_cost_eur", "warehouse_cost_eur",
                    "obsolescence_cost_eur", "stockout_cost_eur",
                    "lost_sales_eur", "expedite_premium_eur", "ordering_cost_eur",
                    "total_cost_of_ownership",
                    "holding_cost_annualized_eur", "tco_annualized_eur"]
    op_metrics = ["inventory_turns", "avg_inventory_eur", "days_of_cover_avg",
                  "n_orders", "avg_order_size"]

    def _print_section(title: str, metrics: list):
        print(f"\n  ── {title} ──")
        sub = df[df["metric"].isin(metrics)]
        if not sub.empty:
            print(sub.to_string(index=False))

    _print_section("Service-Level KPIs", sl_metrics)
    _print_section(f"Cost KPIs (€, {asis.period_days}-day window)", cost_metrics)
    _print_section("Operational KPIs", op_metrics)

    # Per-ABC breakdown if present
    if asis.by_abc_class or tobe.by_abc_class:
        print(f"\n  ── Per ABC Class ──")
        _print_abc_breakdown(asis.by_abc_class, tobe.by_abc_class)

    return df


def _print_abc_breakdown(asis_abc: dict, tobe_abc: dict) -> None:
    classes = sorted(set(asis_abc.keys()) | set(tobe_abc.keys()))
    rows = []
    for cls in classes:
        a = asis_abc.get(cls, {})
        t = tobe_abc.get(cls, {})
        rows.append({
            "ABC":            cls,
            "n_materials":    a.get("n_materials") or t.get("n_materials"),
            "service_asis":   a.get("cycle_service_level"),
            "service_tobe":   t.get("cycle_service_level"),
            "holding_asis":   a.get("holding_cost"),
            "holding_tobe":   t.get("holding_cost"),
            "stockout_asis":  a.get("stockout_cost"),
            "stockout_tobe":  t.get("stockout_cost"),
            "tco_asis":       a.get("tco"),
            "tco_tobe":       t.get("tco"),
            "savings":        (round(a["tco"] - t["tco"], 2)
                               if a.get("tco") is not None and t.get("tco") is not None
                               else None),
        })
    if rows:
        print(pd.DataFrame(rows).to_string(index=False))


# ============================================================
# Sensitivity analysis
# ============================================================
def run_sensitivity_analysis(
    repo: Repository,
    materials_df: pd.DataFrame,
    start: date,
    end: date,
    base_scenario: CostScenario,
) -> pd.DataFrame:
    """Vary key parameters and report how TCO responds.

    Variations:
      • Lead time:    0.8x, 1.0x, 1.2x
      • Demand:       0.9x, 1.0x, 1.1x
      • Holding rate: -20%, base, +20%
    """
    log.info("Running sensitivity analysis (9 backtests, ~3-5 minutes)...")

    variations = [
        # (label, lt_mult, demand_mult, holding_mult)
        ("base",                    1.0, 1.0, 1.0),
        ("lt_-20%",                 0.8, 1.0, 1.0),
        ("lt_+20%",                 1.2, 1.0, 1.0),
        ("demand_-10%",             1.0, 0.9, 1.0),
        ("demand_+10%",             1.0, 1.1, 1.0),
        ("holding_-20%",            1.0, 1.0, 0.8),
        ("holding_+20%",            1.0, 1.0, 1.2),
        ("worst_case",              1.2, 1.1, 1.2),
        ("best_case",               0.8, 0.9, 0.8),
    ]

    results = []
    for label, lt_m, dm_m, hr_m in variations:
        # Build perturbed scenario
        scen = deepcopy(base_scenario)
        scen.holding.capital_cost_rate *= hr_m
        scen.holding.warehouse_rate    *= hr_m
        scen.holding.obsolescence_rate *= hr_m
        scen.holding.insurance_rate    *= hr_m
        scen.holding.shrinkage_rate    *= hr_m

        try:
            asis, tobe = run_scenario(
                repo, materials_df, start, end, scen,
                lead_time_multiplier=lt_m,
                demand_multiplier=dm_m,
            )
            savings = asis.total_cost_of_ownership - tobe.total_cost_of_ownership
            results.append({
                "variation":      label,
                "asis_tco":       asis.total_cost_of_ownership,
                "tobe_tco":       tobe.total_cost_of_ownership,
                "tco_savings":    round(savings, 2),
                "tco_savings_pct": (round(savings / asis.total_cost_of_ownership * 100, 2)
                                    if asis.total_cost_of_ownership else None),
                "asis_service":   asis.cycle_service_level_pct,
                "tobe_service":   tobe.cycle_service_level_pct,
                "asis_stockouts": asis.stockout_days,
                "tobe_stockouts": tobe.stockout_days,
                "period_days":    asis.period_days,
            })
        except Exception as e:
            log.error(f"Variation '{label}' failed: {e}")
            results.append({
                "variation": label, "error": str(e),
            })

    return pd.DataFrame(results)


# ============================================================
# Main
# ============================================================
def main():
    parser = argparse.ArgumentParser(
        description="Backtest As-Is vs To-Be with realistic cost scenarios."
    )
    parser.add_argument("--window-days", type=int, default=60,
                        help="Backtest window in days (default 60, as in the thesis)")
    parser.add_argument("--end", type=str, default=None,
                        help="End date YYYY-MM-DD (default: the dataset's as-of date, "
                             "i.e. the latest stock snapshot / movement)")
    parser.add_argument("--scenario", type=str, default="realistic",
                        choices=list(SCENARIOS.keys()),
                        help="Cost scenario (default: realistic)")
    parser.add_argument("--all-scenarios", action="store_true",
                        help="Run all 3 scenarios and produce a comparison")
    parser.add_argument("--sensitivity", action="store_true",
                        help="Run sensitivity analysis (LT, demand, holding)")
    parser.add_argument("--forecast-method", type=str, default="moving_average",
                        choices=["moving_average", "simple_average", "exponential_smoothing", "auto"],
                        help="Forecasting method of the To-Be agent (default moving_average)")
    parser.add_argument("--out", type=str, default="validation_report.csv")
    args = parser.parse_args()

    end = date.fromisoformat(args.end) if args.end else get_effective_today()
    # Window of exactly `window_days` days, inclusive of both ends
    start = end - timedelta(days=args.window_days - 1)

    log.info(f"Backtest window: {start} → {end} ({args.window_days} days)")

    repo = Repository()
    materials_df = pd.read_sql("SELECT * FROM materials", repo.engine)

    out_dir = Path(args.out).parent if Path(args.out).parent != Path("") else Path(".")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_base = Path(args.out).stem  # filename without extension

    # ─── Path 1: All scenarios comparison ───
    if args.all_scenarios:
        log.info("Running ALL scenarios (conservative / realistic / aggressive)...")
        all_results = []
        for scen_name in SCENARIOS:
            scen = get_scenario(scen_name)
            log.info(f"  Scenario: {scen_name} — {scen.description}")
            asis, tobe = run_scenario(repo, materials_df, start, end, scen)
            print_comparison_report(asis, tobe, scen_name)
            all_results.append((f"{scen_name}_asis", asis))
            all_results.append((f"{scen_name}_tobe", tobe))

        pivot = sensitivity_pivot(all_results)
        all_path = out_dir / f"{out_base}_all_scenarios.csv"
        pivot.to_csv(all_path, index=False)
        log.success(f"Cross-scenario comparison saved to {all_path.absolute()}")

        print(f"\n{'═' * 70}")
        print("  Cross-Scenario Summary (key metrics)")
        print(f"{'═' * 70}")
        print(pivot.to_string(index=False))

    # ─── Path 2: Sensitivity ───
    elif args.sensitivity:
        scen = get_scenario(args.scenario)
        sens_df = run_sensitivity_analysis(repo, materials_df, start, end, scen)
        sens_path = out_dir / f"{out_base}_sensitivity.csv"
        sens_df.to_csv(sens_path, index=False)

        print(f"\n{'═' * 70}")
        print(f"  Sensitivity Analysis (base scenario: {args.scenario})")
        print(f"{'═' * 70}")
        print(sens_df.to_string(index=False))
        log.success(f"Sensitivity report saved to {sens_path.absolute()}")

    # ─── Path 3: Single scenario (default) ───
    else:
        scen = get_scenario(args.scenario)
        log.info(f"Scenario: {args.scenario} — {scen.description}")
        log.info(
            f"  Holding rate breakdown: capital={scen.holding.capital_cost_rate:.0%}, "
            f"warehouse={scen.holding.warehouse_rate:.0%}, "
            f"obsolescence={scen.holding.obsolescence_rate:.0%}, "
            f"total={scen.holding.total_rate:.0%}"
        )
        asis, tobe = run_scenario(repo, materials_df, start, end, scen,
                                  forecast_method=args.forecast_method)
        df = print_comparison_report(asis, tobe, args.scenario)

        out_path = Path(args.out)
        df.to_csv(out_path, index=False)
        log.success(f"Report written to {out_path.absolute()}")

        # Per-ABC breakdown (thesis Table 4.8) as its own CSV
        abc_rows = []
        for cls in sorted(set(asis.by_abc_class) | set(tobe.by_abc_class)):
            a = asis.by_abc_class.get(cls, {})
            t = tobe.by_abc_class.get(cls, {})
            abc_rows.append({
                "abc_class":     cls,
                "n_materials":   a.get("n_materials") or t.get("n_materials"),
                "asis_tco":      a.get("tco"),
                "tobe_tco":      t.get("tco"),
                "savings":       round((a.get("tco") or 0) - (t.get("tco") or 0), 2),
                "savings_pct":   (round(((a.get("tco") or 0) - (t.get("tco") or 0))
                                        / a["tco"] * 100, 2)
                                  if a.get("tco") else None),
                "asis_service":  a.get("cycle_service_level"),
                "tobe_service":  t.get("cycle_service_level"),
                "asis_holding":  a.get("holding_cost"),
                "tobe_holding":  t.get("holding_cost"),
                "asis_stockout": a.get("stockout_cost"),
                "tobe_stockout": t.get("stockout_cost"),
            })
        if abc_rows:
            abc_path = out_dir / f"{out_base}_abc.csv"
            pd.DataFrame(abc_rows).to_csv(abc_path, index=False)
            log.success(f"Per-ABC report written to {abc_path.absolute()}")

    repo.close()


if __name__ == "__main__":
    main()
